# Generated by Django 4.1.7 on 2023-04-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tabelapreco_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabelapreco',
            options={'verbose_name_plural': 'TabelaPrecos'},
        ),
    ]
